import {
  macd,
  aarp,
  chevy,
  disney,
  gm,
  gm2,
  match,
  prime,
  tesla,
} from "./logo";

const data = [
  {
    logo: macd,
    brand_name: "McDonalds",
    status: "Pending",
    item: "Big Mac Jumbo",
    quantity: "34",
    price: "9",
    placed_on: "6/3/22",
  },
  {
    logo: tesla,
    brand_name: "Tesla",
    status: "Refund",
    item: "Model X",
    quantity: "534",
    price: "3000",
    placed_on: "12/2/22",
  },
  {
    logo: gm,
    brand_name: "GM",
    status: "Refund",
    item: "Alternator Car Parts",
    quantity: "132",
    price: "49",
    placed_on: "4/9/23",
  },
  {
    logo: aarp,
    brand_name: "AARP",
    status: "Pending",
    item: "Health Care Package Adult A1",
    quantity: "89",
    price: "299",
    placed_on: "1/2/23",
  },
  {
    logo: disney,
    brand_name: "Disney",
    status: "Confirmed",
    item: "Renewal Subscription",
    quantity: "276",
    price: "23",
    placed_on: "9/4/23",
  },
  {
    logo: prime,
    brand_name: "Prime Theraputics",
    status: "Delivered",
    item: "Natual Oil",
    quantity: "1,098",
    price: "135",
    placed_on: "6/3/22",
  },
  {
    logo: match,
    brand_name: "Match.com",
    status: "Confirmed",
    item: "Renewal Subscription",
    quantity: "4,298",
    price: "48",
    placed_on: "12/2/22",
  },
  {
    logo: chevy,
    brand_name: "Chevy",
    status: "Delivered",
    item: "FX234A",
    quantity: "1,928",
    price: "90",
    placed_on: "4/19/23",
  },
  {
    logo: gm2,
    brand_name: "GM",
    status: "Delivered",
    item: "Car Parts AJZ89B",
    quantity: "640",
    price: "167",
    placed_on: "1/2/23",
  },
];

export default data;
